import { useState } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { db, getSettings } from '../db';
import { Plus, Download } from 'lucide-react';
import { downloadPDF } from '../utils/pdf';

export default function Fees() {
  const [isAdding, setIsAdding] = useState(false);
  const fees = useLiveQuery(() => db.fees.reverse().toArray(), []) || [];

  const handleExportCSV = () => {
    if (fees.length === 0) return alert('No records to export');
    const headers = ['Date', 'Student Name', 'Term/Month', 'Receipt No.', 'Amount', 'Status'];
    const rows = fees.map(f => [
      new Date(f.date).toLocaleDateString(),
      f.studentName,
      f.termOrMonth,
      f.receiptNumber,
      f.amount.toString(),
      f.status,
    ]);

    const csvContent = [
      headers.join(','),
      ...rows.map(e => e.map(val => `"${val}"`).join(','))
    ].join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `fee_records_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportPDF = () => {
    if (fees.length === 0) return alert('No records to export');
    const settings = getSettings();

    const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Financial Report</title>
          <style>
            body { font-family: system-ui, -apple-system, sans-serif; color: #111; line-height: 1.5; padding: 40px; max-width: 800px; margin: 0 auto; }
            .header { display: flex; align-items: center; border-bottom: 2px solid #EEE; padding-bottom: 20px; margin-bottom: 30px; }
            .logo { height: 60px; width: 60px; object-fit: contain; margin-right: 20px; }
            .school-info h1 { margin: 0 0 5px 0; font-size: 20px; color: ${settings.themeColor}; }
            .school-info p { margin: 0; color: #555; font-size: 13px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 12px; }
            th, td { padding: 8px 10px; border: 1px solid #EEE; text-align: left; }
            th { background: #F9F9F9; font-weight: 600; text-transform: uppercase; color: #666; font-size: 11px; }
            td.amount { text-align: right; }
            .total-row { font-weight: bold; background: #F9F9F9; }
            .footer { margin-top: 40px; border-top: 1px solid #EEE; padding-top: 20px; text-align: center; color: #888; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            ${settings.schoolLogo ? `<img src="${settings.schoolLogo}" class="logo" />` : ''}
            <div class="school-info">
              <h1>${settings.schoolName || 'School Manager'}</h1>
              <p>Financial Export - ${new Date().toLocaleDateString()}</p>
            </div>
          </div>

          <h2>Fees Ledger</h2>

          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Student Name</th>
                <th>Term/Month</th>
                <th>Receipt No.</th>
                <th>Amount</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${fees.map(f => `
                <tr>
                  <td>${new Date(f.date).toLocaleDateString()}</td>
                  <td>${f.studentName}</td>
                  <td>${f.termOrMonth}</td>
                  <td>${f.receiptNumber}</td>
                  <td class="amount">$${f.amount.toFixed(2)}</td>
                  <td>${f.status}</td>
                </tr>
              `).join('')}
              <tr class="total-row">
                <td colspan="4" style="text-align: right">Total Paid Intake</td>
                <td class="amount">$${fees.filter(f => f.status !== 'Unpaid').reduce((sum, f) => sum + f.amount, 0).toFixed(2)}</td>
                <td></td>
              </tr>
            </tbody>
          </table>

          <div class="footer">
            Generated by Comfort School Manager &bull; ${new Date().toLocaleDateString()}
          </div>
        </body>
      </html>
    `;

    downloadPDF(html, `Fee_Records_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="flex flex-col h-full space-y-6">
      <div className="flex justify-between items-center flex-wrap gap-4">
        <div>
          <h2 className="text-2xl font-bold text-gray-900 tracking-tight">Fees Ledger</h2>
          <p className="text-gray-500 mt-1">Manage school fee payments and tracking.</p>
        </div>
        <div className="flex items-center gap-2">
          <button 
            onClick={handleExportCSV}
            className="px-4 py-2 rounded-lg font-medium flex items-center gap-2 text-primary border border-primary/20 hover:bg-primary/5 transition-colors"
          >
            <Download className="w-4 h-4" />
            CSV
          </button>
          <button 
            onClick={handleExportPDF}
            className="px-4 py-2 rounded-lg font-medium flex items-center gap-2 text-primary border border-primary/20 hover:bg-primary/5 transition-colors"
          >
            <Download className="w-4 h-4" />
            PDF
          </button>
          <button 
            onClick={() => setIsAdding(true)}
            className="bg-primary text-white px-4 py-2 rounded-lg font-medium flex items-center gap-2 hover:bg-primary/90 transition-colors"
          >
            <Plus className="w-4 h-4" />
            Record Payment
          </button>
        </div>
      </div>

      <div className="bg-white border border-gray-200 rounded-xl overflow-hidden flex-1 shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse min-w-[600px]">
            <thead className="bg-gray-50 text-gray-500 text-sm border-b border-gray-200">
              <tr>
                <th className="py-3 px-4 font-medium">Date</th>
                <th className="py-3 px-4 font-medium">Student Name</th>
                <th className="py-3 px-4 font-medium">Term/Month</th>
                <th className="py-3 px-4 font-medium">Receipt No.</th>
                <th className="py-3 px-4 font-medium text-right">Amount</th>
                <th className="py-3 px-4 font-medium w-32">Status</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 text-sm">
              {fees.length === 0 ? (
                <tr><td colSpan={6} className="py-8 text-center text-gray-500">No payment records found.</td></tr>
              ) : (
                fees.map(fee => (
                  <tr key={fee.id} className="hover:bg-gray-50">
                    <td className="py-3 px-4 text-gray-600">{new Date(fee.date).toLocaleDateString()}</td>
                    <td className="py-3 px-4 font-medium text-gray-900">{fee.studentName}</td>
                    <td className="py-3 px-4 text-gray-600">{fee.termOrMonth}</td>
                    <td className="py-3 px-4 text-gray-600 font-mono text-xs">{fee.receiptNumber}</td>
                    <td className="py-3 px-4 font-medium text-gray-900 text-right">${fee.amount.toFixed(2)}</td>
                    <td className="py-3 px-4">
                      <span className={`px-2.5 py-1 rounded-full text-xs font-medium inline-flex items-center
                        ${fee.status === 'Paid' ? 'bg-green-100 text-green-700' : ''}
                        ${fee.status === 'Partial' ? 'bg-blue-100 text-blue-700' : ''}
                        ${fee.status === 'Unpaid' ? 'bg-red-100 text-red-700' : ''}
                      `}>
                        {fee.status}
                      </span>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {isAdding && <FeeModal onClose={() => setIsAdding(false)} />}
    </div>
  );
}

function FeeModal({ onClose }: { onClose: () => void }) {
  const [studentName, setStudentName] = useState('');
  const [term, setTerm] = useState('');
  const [receipt, setReceipt] = useState('');
  const [amount, setAmount] = useState('');
  const [status, setStatus] = useState<'Paid'|'Partial'|'Unpaid'>('Paid');

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    await db.fees.add({
      studentId: 0, // In full app, select from dropdown
      studentName: studentName,
      termOrMonth: term,
      receiptNumber: receipt,
      amount: parseFloat(amount) || 0,
      status: status,
      date: new Date().toISOString()
    });
    onClose();
  };

  return (
    <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-xl shadow-xl w-full max-w-md overflow-hidden p-6">
        <h3 className="font-bold text-lg mb-4">Record Payment</h3>
        <form onSubmit={handleSave} className="space-y-4">
          <div>
            <label className="block text-sm font-medium mb-1">Student Name</label>
            <input required type="text" value={studentName} onChange={e=>setStudentName(e.target.value)} className="w-full px-3 py-2 border rounded-md" />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium mb-1">Term / Month</label>
              <input required type="text" value={term} onChange={e=>setTerm(e.target.value)} className="w-full px-3 py-2 border rounded-md" placeholder="e.g. Term 1" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Receipt No.</label>
              <input required type="text" value={receipt} onChange={e=>setReceipt(e.target.value)} className="w-full px-3 py-2 border rounded-md" />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4">
             <div>
              <label className="block text-sm font-medium mb-1">Amount Paid</label>
              <input required type="number" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} className="w-full px-3 py-2 border rounded-md" />
            </div>
            <div>
              <label className="block text-sm font-medium mb-1">Status</label>
              <select value={status} onChange={e=>setStatus(e.target.value as any)} className="w-full px-3 py-2 border rounded-md">
                <option value="Paid">Paid</option>
                <option value="Partial">Partial</option>
                <option value="Unpaid">Unpaid</option>
              </select>
            </div>
          </div>
          <div className="flex justify-end gap-3 pt-4">
            <button onClick={onClose} type="button" className="px-4 py-2 border rounded-lg">Cancel</button>
            <button type="submit" className="px-4 py-2 bg-primary text-white rounded-lg">Save Record</button>
          </div>
        </form>
      </div>
    </div>
  );
}
